development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://:p6b93411d9806aeab70110abb7410fe3f6e112dce1ef1d7ff953664650809ba28@ec2-50-16-82-63.compute-1.amazonaws.com:29619") { "redis://localhost:6379/1" } %>
  channel_prefix: fishcord_production
